media: 
  - name: blog_media
    label: Blog Media
    input: blog/images
    output: /blog/images

  - name: static_menu_media
    label: Static Menu Media
    input: docs/static-menu/images
    output: /docs/static-menu/images
    
  - name: our_identity_media
    label: Our Identity Media
    input: static/img/Our Identity
    output: /img/Our Identity
    
  - name: our_people_media
    label: Our People Media
    input: static/img/Our People
    output: /img/Our People
    
  - name: our_practices_media
    label: Our Practices Media
    input: static/img/Our Practices
    output: /img/Our Practices

  - name: authors_media
    label: Authors Pictures
    input: blog/images/authors
    output: /blog/images/authors
    
content:
  - name: blog
    label: Blog
    type: collection
    path: 'blog'
    view:
      fields: [ title, description, date, authors, image, slug, tags, body ]
    fields:
      - type: string
        name: title
        label: Title
        required: true
      
      - type: string
        name: description
        label: Description
        required: true
      
      - type: string
        name: date
        label: Date
        required: false
      
      - name: authors
        label: Authors
        type: string
        list: false
      
      - type: image
        name: cover_image
        label: Cover Image
        required: false
        options:
          media: blog_media
      
      - type: image
        name: image
        label: Image
        required: false
        options:
          media: blog_media
      
      - type: string
        name: slug
        label: Slug
        required: false
      
      - type: string
        name: tags
        label: Tags
        list: true
        required: false
      
      - type: rich-text
        name: body
        label: Body
        options:
          media: blog_media
        
  - name: identity
    label: Our Identity
    type: collection
    path: 'docs/autogenerated-menu/Our Identity'
    view:
      fields: [ title, description, sidebar_position, slug, pagination_next, pagination_prev, tags, image, body ]
    fields:
      - type: string
        name: title
        label: Title
        required: false
      
      - type: string
        name: description
        label: Description
        required: false
      
      - type: number
        name: sidebar_position
        label: Sidebar Position
        required: true
      
      - type: string
        name: slug
        label: Slug
        required: false
      
      - type: string
        name: pagination_next
        label: Next Page
        required: false
      
      - type: string
        name: pagination_prev
        label: Previous Page
        required: false
      
      - type: string
        name: tags
        label: Tags
        list: true
        required: false

      - type: image
        name: image
        label: Image
        required: false
        options:
          media: our_identity_media
      
      - name: body
        label: Body
        type: rich-text
        options:
          media: our_identity_media

  - name: people
    label: Our People
    type: collection
    path: 'docs/autogenerated-menu/Our People'
    view:
      fields: [ title, description, sidebar_position, slug, pagination_next, pagination_prev, tags, image, body ]
    fields:
      - type: string
        name: title
        label: Title
        required: false
      
      - type: string
        name: description
        label: Description
        required: false
      
      - type: number
        name: sidebar_position
        label: Sidebar Position
        required: true
      
      - type: string
        name: slug
        label: Slug
        required: false
      
      - type: string
        name: pagination_next
        label: Next Page
        required: false
      
      - type: string
        name: pagination_prev
        label: Previous Page
        required: false
      
      - type: string
        name: tags
        label: Tags
        list: true
        required: false

      - type: image
        name: image
        label: Image
        required: false
        options:
          media: our_people_media
      
      - name: body
        label: Body
        type: rich-text
        options:
          media: our_people_media

  - name: practices
    label: Our Practices
    type: collection
    path: 'docs/autogenerated-menu/Our Practices'
    view:
      fields: [ title, description, sidebar_position, slug, pagination_next, pagination_prev, tags, image, body ]
    fields:
      - type: string
        name: title
        label: Title
        required: false
      
      - type: string
        name: description
        label: Description
        required: false
      
      - type: number
        name: sidebar_position
        label: Sidebar Position
        required: true
      
      - type: string
        name: slug
        label: Slug
        required: false
      
      - type: string
        name: pagination_next
        label: Next Page
        required: false
      
      - type: string
        name: pagination_prev
        label: Previous Page
        required: false
      
      - type: string
        name: tags
        label: Tags
        list: true
        required: false

      - type: image
        name: image
        label: Image
        required: false
        options:
          media: our_practices_media
      
      - name: body
        label: Body
        type: rich-text
        options:
          media: our_practices_media

  - name: static-menu
    label: Static Menu
    type: collection
    path: 'docs/static-menu'
    view:
      fields: [ title, description, sidebar_position, slug, pagination_next, pagination_prev, tags, image, body ]
    fields:
      - type: string
        name: title
        label: Title
        required: false
      
      - type: string
        name: description
        label: Description
        required: false
      
      - type: number
        name: sidebar_position
        label: Sidebar Position
        required: true
      
      - type: string
        name: slug
        label: Slug
        required: false
      
      - type: string
        name: pagination_next
        label: Next Page
        required: false
      
      - type: string
        name: pagination_prev
        label: Previous Page
        required: false
      
      - type: string
        name: tags
        label: Tags
        list: true
        required: false

      - type: image
        name: image
        label: Image
        required: false
        options:
          media: static_menu_media
      
      - name: body
        label: Body
        type: rich-text
        options:
          media: static_menu_media
