name: "Merge to main"
on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "blog/**"

jobs:
  trigger-build:
    name: "Trigger Handbook Build & Deploy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Trigger public infrastructure build"
        id: api-trigger-public
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/burendouk/burendo-handbook-infrastructure/dispatches \
            -d '{"event_type":"content-updated"}'
        working-directory: .
        env:
          GITHUB_TOKEN: ${{ secrets.GHA_TOKEN }}

      - name: "Trigger private infrastructure build"
        id: api-trigger-private
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/burendouk/burendo-handbook-infrastructure/dispatches \
            -d '{"event_type":"content-updated-private"}'
        working-directory: .
        env:
          GITHUB_TOKEN: ${{ secrets.GHA_TOKEN }}
