name: Update Confluence Labels

on:
  pull_request:
    types:
      - closed
    branches:
      - main
env:
  CONFLUENCE_DOMAIN: burendo

jobs:
  update_labels:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: scripts

    - name: Update Confluence labels
      env:
        CONFLUENCE_AUTH_TOKEN: ${{ secrets.CONFLUENCE_AUTH_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CONFLUENCE_DOMAIN: $CONFLUENCE_DOMAIN
        GITHUB_REPOSITORY: ${{ github.event.repository.name }}
        INPUT_PR_NUMBER: ${{ github.event.pull_request.number }}
      run: python post_merge.py
      working-directory: scripts
